# Generated by Django 2.1.5 on 2020-10-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphs.Graph'),
        ),
    ]
