# Generated by Django 2.1.5 on 2020-10-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_auto_20201023_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='numbers',
        ),
    ]
