# Generated by Django 2.1.5 on 2020-10-24 03:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_remove_graph_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=210), blank=True, default=list, size=None),
        ),
    ]
