# Generated by Django 2.1.5 on 2020-10-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0004_auto_20201010_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='timer',
            field=models.BigIntegerField(),
        ),
    ]
