# Generated by Django 2.1.5 on 2020-10-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='price',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='task',
            name='summary',
        ),
    ]
