# Generated by Django 2.1.5 on 2020-10-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20201007_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudUser',
        ),
    ]
